### ISSUE TITLE
requestAnimationFrame is not defined 

### ISSUE THREAD

**Issue by deividas-transfergo** [Stanko/animated-scroll-to#1]
I have an issue with old android 4.3 native browser. requestAnimationFrame is not supported for that version.

My suggestion is create a function which will check for requestAnimationFrame.
`var requestAnimFrame = (function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})();`

and instead of requestAnimationFrame use it requestAnimFrame

**Comment by Stanko** [comment]
Hello, I would like to keep this library small, so I don't want to include polyfill for the `requestAnimationFrame` in the library itself. It is easy to add in you application, as it is mentioned in the readme. 
Thanks!
