### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by eirikurn** [Stanko/animated-scroll-to#10]
I was hoping to use this to implement a horizontal carousel. I was sad to see that it only supports vertical scrolling.

Would this be difficult to add?

**Comment by Stanko** [comment]
Hello @eirikurn,
I will have that in mind and try to add it in one of the next releases. I can't really promise you the exact date, but I'll do my best to squeeze it in.

Cheers!

**Comment by eirikurn** [comment]
Woohoo! Thank you.
