### ISSUE TITLE
Custom easing

### ISSUE THREAD

**Issue by andy-hook** [Stanko/animated-scroll-to#11]
Animated scroll is perfect for my use case except I would like to use a different easing curve. Have you considered adding support for custom curve functions? If not do you have any advice on the best way to modify the code to alter the current easing?

Many thanks in advance.

**Comment by Stanko** [comment]
Hey @andy-hook,
I recently started version 2, and one of things I will add is optional custom easing. I am playing with an idea of including multiple easings to choose from, but I'm afraid of bloating a library.

I plan to release v2 in next week or two.

Cheers!

**Comment by andy-hook** [comment]
Thanks for getting back so quickly. I was attempting to modify this line earlier but seem to run into issues with unintended scroll jumping, if you have a spare moment do you think you could provide me a code example using a different curve? or how I might plug in a common ease eg: https://gist.github.com/gre/1650294

I know you must be busy but this would be a huge help for me. Thank you.

**Comment by Stanko** [comment]
No worries, but thanks for being considerate.

I think I actually used those functions when I was writing the first version 🙂 

Anyway I used `easeOutCubic`
```
  easeOutCubic: function (t) { return (--t)*t*t+1 },
```

```
      var t = (timeDiff / duration) - 1;
      var easing = t * t * t + 1;
      var scrollPosition = Math.round(initialScrollPosition + (diff * easing));
```

**Comment by andy-hook** [comment]
Oh! it was the - 1 that I was forgetting to remove from the previous line.

Would be great to be able to pass this custom curve via an opt in version 2 depending on how you approach this, for now I'll use my fork but will switch to an NPM import for version 2.

Thanks again man, much appreciated.

**Comment by Stanko** [comment]
You are welcome, glad it worked!
