### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by kyleoliveiro** [Stanko/animated-scroll-to#18]
When `cancelOnUserAction` is set to `false`, Chrome throws the following error multiple times during an animated scroll:

```
Unable to preventDefault inside passive event listener invocation.    [animated-scroll-to.js:134]
```

**Comment by Stanko** [comment]
Hello @kyleoliveiro,
For now, you need to set `passive: false` in that scenario. I'll make sure to do it under the hood, when `cancelOnUserAction` is set to `false`.

Cheers!

**Comment by Stanko** [comment]
Updated documentation, library and published.
https://github.com/Stanko/animated-scroll-to/commit/6f05366612c2e106667faf1f65d24541bc09a32c#diff-03c66a80d920d1ef8a30427d3f240ed7R32
