### ISSUE TITLE
navigation with keydown is disabled

### ISSUE THREAD

**Issue by ctf0** [Stanko/animated-scroll-to#20]
is it possible to also support navigation with the keyboard keys ?

atm in my app instead of only relying on the mouse, i also offer to use the keyboard arrow keys which is much easier and quicker than the mouse,
hoever atm the lib use the keydown event to stop the scroll
https://github.com/Stanko/animated-scroll-to/blob/a163140fc0496e08e882ca25335d4223407ea5f6/animated-scroll-to.js#L160

so is there a way to add an option to enable that for those who needs it ?

**Comment by Stanko** [comment]
Hello @ctf0,
I'm not sure if I understand your usecase, but can you try using `cancelOnUserAction: false`?

**Comment by ctf0** [comment]
using `cancelOnUserAction: false` means that why the user try to scroll while the lib is working he wont be able to cancel the scrolling.

what this pr is for is basically add an option to decide whether using the keyboard keys will disable the scrolling or not.

this opens the way to use keydown events with keys like `right,left,top,bottom, etc..` to trigger the scroll

**Comment by ctf0** [comment]
its okay, np, can u plz first take a look at the `cancelOnUserAction` in the lib 

https://github.com/Stanko/animated-scroll-to/blob/a163140fc0496e08e882ca25335d4223407ea5f6/animated-scroll-to.js#L159

using the option will disable those 2 things, while i only want to disable/enable the `keydown` event
