### ISSUE TITLE
Can't get animateScrollTo to work when passed with option object

### ISSUE THREAD

**Issue by aajkishore** [Stanko/animated-scroll-to#25]
I have a `scrollTo` function which is invoked on a button click.

````
scrollTo = (elem) => {
    animateScrollTo(document.getElementById(elem));
};
````
However, when I try to add some offset to adjust for padding, it doesn't scroll at all.

````
scrollTo = (elem) => {
    animateScrollTo(1000, {
      offset: 100,
      element: document.getElementById(elem),
    });
  };
````

**Comment by Stanko** [comment]
Hello @aajkishore,
You are using it wrong, the first param is either desired scroll position or element to scroll to. Element in the options is the element that should be scrolled, by default it is `body`

Your second example should look like this:
```js
  scrollTo = (elem) => {
    animateScrollTo(document.getElementById(elem), {
      offset: 100,
    });
  };
```

Cheers!
