### ISSUE TITLE
"onComplete" never gets called when user interrupts scroll animation

### ISSUE THREAD

**Issue by mciastek** [Stanko/animated-scroll-to#26]
When you set `cancelOnUserAction` to `true` and after scroll animation is interrupted by user's action, the `onComplete` never gets called. It would be nice to know if animated completed even if it was interrupted in the middle. I would like to help with PR, so just let me know if that's a good idea.

https://github.com/Stanko/animated-scroll-to/blob/636752b47f7cf5434966986acc77f15462a69ae7/animated-scroll-to.js#L140-L143

**Comment by Stanko** [comment]
Hey @mciastek,

You are correct, it doesn't get called in that scenario. I thought about it for a while, and I think better solution would be to add a new property `onUserCancelation` (name is open for suggestion 🙈).

Honestly I never run into scenario where I needed that.

What do you think?

**Comment by mciastek** [comment]
Hi @Stanko! Thanks for responding to my issue!

Honestly, I'm not sure if I need to know if scroll animation has been interrupted by user or not. I would prefer having only one callback which tells me that animation ended. Simple as that. If such information is required I would add an argument to `onComplete` callback, which tells you if animated has been ended before it's done. What do you think about it?

**Comment by Stanko** [comment]
It probably makes sense to have one callback, and pass a boolean argument to it `canceled`. I'll create a change soon.

**Comment by mciastek** [comment]
Great! I'm happy to help with PR if needed.

**Comment by Stanko** [comment]
Published in v1.3.0 🎉 `onComplete` now receives a boolean argument `isCanceledByUserAction`

https://github.com/Stanko/animated-scroll-to/pull/27
