### ISSUE TITLE
if element and cancelOnUserAction passed the whole page can't scroll

### ISSUE THREAD

**Issue by DavidNeiOs** [Stanko/animated-scroll-to#28]
Hello,
I had this issue while working with the library, I pass an horizontal element to be animated and also `cancelOnUserAction: false` but the whole page loses the scroll behaviour.

I fixed it by changing the `window` listeners of `wheel, scroll and touch start` to `options.element`

<img width="983" alt="Screen Shot 2019-09-13 at 7 45 32 PM" src="https://user-images.githubusercontent.com/40399577/64900691-b990f480-d660-11e9-9687-1aa4f5a89f62.png">

**Comment by Stanko** [comment]
Hello @DavidNeiOs,
Good catch, can you please open a PR with changes?
Thank you!

**Comment by DavidNeiOs** [comment]
@Stanko PR made :)

**Comment by Stanko** [comment]
Published in 1.3.1 🎉 
Thank you for help!
