### ISSUE TITLE
V2 - Cannot find module 'animated-scroll-to' from 'scrollTo.js'

### ISSUE THREAD

**Issue by louiscloutierdakis** [Stanko/animated-scroll-to#32]
In v2 this code
`import animateScrollTo from 'animated-scroll-to';`

Get me this error : Cannot find module 'animated-scroll-to' from 'scrollTo.js'

I use create-react-app vanilla without typescript.

**Comment by Stanko** [comment]
Should be fixed with 2.0.1
Sorry about that, I had a leftover line in `.npmignore`
