### ISSUE TITLE
Switching to commonjs instead of es2015

### ISSUE THREAD

**Issue by louiscloutierdakis** [Stanko/animated-scroll-to#33]
A lot of big libraries in react written in typescript are using module commonjs for a better compatibility. You can see here material-ui https://github.com/mui-org/material-ui/blob/master/tsconfig.json#L3

Could you consider switching to commonjs in compilerOptions module?

**Comment by Stanko** [comment]
I will take a look, thank you!

**Comment by Stanko** [comment]
Fixed in v2.0.2 https://github.com/Stanko/animated-scroll-to/commit/2d3854fd4fd79a8bcea8d0f6730419b53be2b811
🎉
