### ISSUE TITLE
Typescript typings are out of date and not stored in the the repo

### ISSUE THREAD

**Issue by sanddigital** [Stanko/animated-scroll-to#36]
It looks like the typings for this library are not properly 'done' yet. Looks like it was only updated to use typescript 30 days ago.

The original index.d.ts typings need to be removed and the the up to date typings need to be defined.

Looks like the typings in npm package are the generated ones by tsc --declaration (they are included in the npm package)
https://github.com/Stanko/animated-scroll-to/blob/master/package.json#L12

And the type definitions are defined by package.json
https://github.com/Stanko/animated-scroll-to/blob/master/package.json#L6

It however also looks like the output folder ./lib is git ignored which is why they're probably not in the repo.
https://github.com/Stanko/animated-scroll-to/blob/master/.gitignore#L9

**To do**
1. Exclude 'lib' from `.gitignore`
2. Include the `animated-scroll-to.d.ts` type definition in the repo
2. Delete v1 `index.d.ts` type definition

**Comment by Stanko** [comment]
Hey,
Thank you for the PR. I will look into and merge as soon as I can. I’m on vacation at the moment, so it might take me couple of days.
Cheers!

**Comment by Stanko** [comment]
Hello @sanddigital, 

I finally got some time to check your PR, and thank you for doing it, I'll make sure to merge those changes. But I don't get why would I include typings file in the repo. I left out compiled `lib` folder on purpose. To my knowledge it is enough that typings is available on npm.

Am I missing something?

Thank you!

**Comment by Stanko** [comment]
I decided to do what you suggested, and made some trivial naming changes. Published [2.0.4](https://www.npmjs.com/package/animated-scroll-to/v/2.0.4)

Thank you again! I'll close the PR.

**Comment by sanddigital** [comment]
HI @Stanko thanks for taking a look at this!

I noticed that you didn't merge the changes I put in. One of those changes was to `export interface` - which makes the typings available to consumers, without them being exported consumers can't utilise them.

To answer the question on including typings in the repo, it just leaves out the mystery of where they come from when looking through the repo.

Can you consider adding the `exports` as I had done in the PR?

Thanks

**Comment by Stanko** [comment]
Will do! I’m traveling today, I’ll probably get to it tomorrow.

**Comment by Stanko** [comment]
Should be fine now:
https://github.com/Stanko/animated-scroll-to/blob/c0ecbca48175e1d55aca24aad6b069829c655d9b/lib/animated-scroll-to.d.ts
