### ISSUE TITLE
can you remove comment script tag 

### ISSUE THREAD

**Issue by fenghuixue** [Stanko/animated-scroll-to#38]
comment script tag cause some problem when i use in iframe in development mode, can you remove it?
in 352, thank you.
<script src="https://unpkg.com/es6-promise/dist/es6-promise.auto.min.js"></script>

**Comment by Stanko** [comment]
Hello @fenghuixue,
Not sure what are you talking about? Is `es6-promise` creating a problem for you? Please specify the exact thing that is the problem and how to replicate it, so I can test it. I'm on vacation at the moment, so it will probably take me couple of days.

Cheers!

**Comment by fenghuixue** [comment]
> Hello @fenghuixue,
> Not sure what are you talking about? Is `es6-promise` creating a problem for you? Please specify the exact thing that is the problem and how to replicate it, so I can test it. I'm on vacation at the moment, so it will probably take me couple of days.
> 
> Cheers!
just this line.
![image](https://user-images.githubusercontent.com/11567029/67656035-9c548300-f98d-11e9-8849-f2881c2742ac.png)

**Comment by Stanko** [comment]
I honestly don't understand how does that line can make a problem, it is a comment and ignored by interpreters.

**Comment by fenghuixue** [comment]
> I honestly don't understand how does that line can make a problem, it is a comment and ignored by interpreters.

It's because my script inject at wrong way, thank you. I fixed it
