### ISSUE TITLE
Compatible with react

### ISSUE THREAD

**Issue by Xx-AmrHossam-xX** [Stanko/animated-scroll-to#39]
Hi,Is this library compatible with react ?..... i mean does it follow the guidelines of react of not manipulating the DOM directly ?

**Comment by Stanko** [comment]
Hello, library doesn't alter the DOM at all. It just scrolls the page (or element).

**Comment by Xx-AmrHossam-xX** [comment]
animateScrollTo(document.querySelector("#xcv")); .......isn't document.querySelector considered as dom manipulation ?

**Comment by Stanko** [comment]
It is actually on user’s side. Library does not access DOM nor alter it.

Cheers!

**Comment by Xx-AmrHossam-xX** [comment]
ok Thanks,i don't know where to post my questions since these are all obviously questions not issues and i do wana thank you for your quick reply .I would really appreciate it if you could confirm that the following code is how i'm supposed to use your library in create-react-app : 
``
class App extends Component {
  b(){
    animateScrollTo(document.querySelector("#xcv"));
  }
  render() {
    return (
      <div className="App">
<Button color="primary" onClick={this.b.bind(this)}>primary</Button>
<p>many paragraphs here to show the effect </p>
<h1 id="xcv">zzzzzzzzz</h1>

      </div>
    );
  }
}

export default App;
``
Of course there is more code but i just added what really mattered and simplified it as much as possible.

**Comment by Stanko** [comment]
I cooked up a small how-to example:
https://codesandbox.io/s/gracious-flower-07r5j

It shows how to scroll on mount and on click. Both to specific position and to a element.

Cheers!

**Comment by Xx-AmrHossam-xX** [comment]
Excellent job,This was what i'd meant from the beginning ; using refs is a more react-friendly way to do it but since i'm a novice developer i can't really argue with your previous reply "It is actually on user’s side. Library does not access DOM nor alter it." .

**Comment by VasilyShelkov** [comment]
Would you be happy with me adding something to the docs in an MR about using this library with ReactJS? 

It's immensely useful and really effective 👍 💯

**Comment by Stanko** [comment]
Sorry, but I really don't get it, it is a single function you need to call somewhere in the lifecycle, what is there to document?

**Comment by VasilyShelkov** [comment]
I just thought that having the code sandbox and showing an example is approachable to more people than having to guess if it will work as expected with ReactJS.

Up to you, it's only an idea which is why I am asking first before just creating a pull request :)
