### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by nikoloza** [Stanko/animated-scroll-to#4]
Hey,

it works very well on all desktop browsers, but not on iOS ones.

**Comment by Stanko** [comment]
Just tested it on ios 10 iphone 6s, ipad mini and ios9 iphone 6s plus and demo works in every single one.

**Comment by nikoloza** [comment]
Yes, I also did and your example works perfectly. Sorry about this, I'm about to debug one now.

**Comment by Stanko** [comment]
No problem, just please provide more info when you are submitting issue to a open source project. Device you tried, what is happening, stack trace or console errors if any...

Hope you get it, cheers!

**Comment by nikoloza** [comment]
Hey @Stanko,

Thanks for your very quick response. After digging, found 2 issues.

1. Running command from console works, but not on onClick handler.
2. It works if you avoid assigning `requestID` from this line, and just invoke function https://github.com/Stanko/animated-scroll-to/blob/master/animated-scroll-to.js#L135

This may seems strange, maybe you know what can be causing this?

**Comment by Stanko** [comment]
Is there any errors in the console, can you try connecting it to Safari's web inspector?
https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html

**Comment by nikoloza** [comment]
@Stanko Thanks for your effort. I'm aware of this, the bug was that I was invoking your function inside my `touchstart` event listener, which came into conflict with this one: https://github.com/Stanko/animated-scroll-to/blob/master/animated-scroll-to.js#L86.

Solution was to use `touchend` from my side.

**Comment by nikoloza** [comment]
Or `stopPropagation`
