### ISSUE TITLE
Limit scroll directions

### ISSUE THREAD

**Issue by mitko993** [Stanko/animated-scroll-to#41]
Hello,

When you pass an element to `animatedScrollTo(myElement)` it will scroll to it in both direction (horizontal and vertical), but in my case i wanted to scroll only vertically to that element.

Do you think it's possible to add properties which limits the scroll only in one direction?

**Comment by Stanko** [comment]
Hello @mitko993 ,
As a workaround you can get element's top using `getBoundingClientRect`
```js
const top = myElement.getBoundingClientRect().top + window.pageYOffset;

animatedScrollTo(top);
```

I'm not sure If I want to add one more variation to the already fairly complicated method signature.

Cheers!
