### ISSUE TITLE
Chrome console warning

### ISSUE THREAD

**Issue by ardalann** [Stanko/animated-scroll-to#6]
I'm getting this warning in my Chrome inspector console from this package:
```
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. 
Consider marking event handler as 'passive' to make the page more responsive.
```

[What it is](https://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responsive)

[Solution](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

I'm going to try to create a PR soon with a fix.

**Comment by Stanko** [comment]
Hello @ardalann,
Thanks for the effort, I'll check everything when I get home.
Cheers!

**Comment by ardalann** [comment]
It seems like you are intentionally trying to cancel user interactions when scrolling. If that's the case, we should probably ignore the warning. However, it would have been nice if we had an option for canceling the animation on user interaction instead.

**Comment by Stanko** [comment]
Sorry for the mighty delayed response. I just saw this again, and there is `cancelOnUserAction` option already. If that solves it, I think we can close the issue.

**Comment by Stanko** [comment]
Fixed by https://github.com/Stanko/animated-scroll-to/pull/14
