### ISSUE TITLE
It don't work on my mobile applications

### ISSUE THREAD

**Issue by dylanass** [Stanko/animated-scroll-to#60]
It don't work on my mobile applications , can I need [smoothscroll.polyfill](https://github.com/iamdustan/smoothscroll) to compatibility ?

**Comment by Stanko** [comment]
Hello, `animated-scroll-to` is not using native scroll, but uses javascript to move page scroll. If it fits your needs, `behavior: smooth` (with polyfill) might be a better solution.

Cheers!

**Comment by Aftea-c** [comment]
`animated-scroll-to` is using window.requestAnimationFrame() ? 

Maybe I'm not describing it accurately, it can word , but lose smooth effect.

**Comment by Stanko** [comment]
Correct, library is using `requestAnimationFrame`:
https://github.com/Stanko/animated-scroll-to/blob/master/src/animated-scroll-to.ts#L382

**Comment by Aftea-c** [comment]
thanks for your answer!   

I will check for my code. 

Cheers!
