### ISSUE TITLE
Set default options during import

### ISSUE THREAD

**Issue by simarlab** [Stanko/animated-scroll-to#63]
Hi @Stanko , first of all thanks for the library, it solve a big need!
My question is about setting the default options during the import.
Is it possibile?
`import animateScrollTo from 'animated-scroll-to';
window.animateScrollTo = animateScrollTo;`
What i've to do before assigning it to global window object?

**Comment by Stanko** [comment]
Hello @simarlab,

Library wasn't made to be used directly in a browser. You'll have to add a transpiler of some sort to make it happen.

For example for the demo page, I do exactly what you described above:
https://github.com/Stanko/animated-scroll-to/blob/v2/docs/docs.ts

but I then let TypeScript compiler generate plain javascript file that can be used in a browser:
https://github.com/Stanko/animated-scroll-to/blob/v2/docs/docs.js

Hope that helps, cheers!

P.S. Version 1 works directly in a browser:
https://github.com/Stanko/animated-scroll-to/tree/v1

**Comment by simarlab** [comment]
@Stanko thanks for the fast reply, but you didn't gave me an answer on my question. Maybe I was confusing while explaining it. :)
I know the things you mentioned, and  i'm using a webpack compiler to import library and then assigning it to the window in order to make it usable..and it's working perfectly.
What i would like to know if is possibile to edit the default configuration once or if i need to pass the values every time i call the method.
I hope to have explained better my issue, thanks for now!

**Comment by Stanko** [comment]
Oh, I have missunderstood your question, my bad, sorry 🙈 

Unfortunately, at the moment there is no way to override default options globally. 

You have to define your options and pass them in each call. To make things a little bit cleaner, you can wrap `animateScrollTo` in your own method like this:

```js
const newDefaultOptions = {
  maxDuration: 1000,
  minDuration: 500,
};

function myScrollTo(elementOrPosition, userOptions) {
  // Allow to override the options
  const options = {
    ...newDefaultOptions,
    ...userOptions,
  }

  animateScrollTo(elementOrPosition, options);
}
```

Hope this time I answered the question 😄

**Comment by simarlab** [comment]
Don't worry, can happen! 
Ok, now it's totally clear. 
Thanks again for you help, i'll do as you suggested!
