### ISSUE TITLE
[feature] add support for scroll-to element and locate it from bottom

### ISSUE THREAD

**Issue by Yaphet2015** [Stanko/animated-scroll-to#65]
I want to scroll to an element

And it needed to be located from the bottom of the screen.

Just like `element.scrollIntoView({block: "end"})`

**Comment by Stanko** [comment]
Hey @JasonYan2015,
You can create a simple wrapper function like this:

```js
function scrollToBottom(element, options) {
  const y = window.scrollY + element.getBoundingClientRect().bottom;
  animateScrollTo(y, options);
}

const element = document.querySelector('.my-element');
scrollToBottom(element, options);
```

I really try to avoid adding too many features, so I hope this works for you.
Cheers!
