### ISSUE TITLE
"cancelOnUserAction" option value cannot be FALSE

### ISSUE THREAD

**Issue by ZA-ATOOT** [Stanko/animated-scroll-to#9]
When you set "cancelOnUserAction" to FALSE, the function ignores it because it checks its value and because it is FALSE it takes the default value.

**Comment by Stanko** [comment]
Fixed in [v1.1.8](https://github.com/Stanko/animated-scroll-to/commit/cf1acd41d28906cd9257bde7043134dbeb9898d4).
